version: '3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony
    ports:
      - 8080:80

  node:
    build:
      context: ./docker/node
    volumes:
      - .:/var/www
    command: ["tail", "-f", "/dev/null"]
    networks:
      - symfony

networks:
  symfony:
